/* Even Fibonacci numbers
Problem 2 Each new term in the Fibonacci sequence is generated by adding the
 previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four
 million, find the sum of the even-valued terms.
*/

/* Pseudo code
Step 1: Initialize vars with first two Fib terms
Step 2: While loop on term not exceeding 4million
Step 3: Add even term to a running Sum variable
*/

function fibAddEven(maxTermValue){
    // Start with the first 2 terms being 1 and 2
    var evenSum = 2
    var newFib = 0
    var currFib = 2
    var prevFib = 1

    newFib = currFib + prevFib
    
    while ( newFib <= maxTermValue ) {
        if (newFib % 2 == 0){
            evenSum = evenSum + newFib
        }

        prevFib = currFib
        currFib = newFib
        newFib = currFib + prevFib
    }
console.log("Sum of Even Fibonacci Terms with max term value of " + maxTermValue + " = " + evenSum)
}